## AllClassifier Gradient Boosteed Classifier

In [1]:
from sklearn.datasets import make_classification
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import train_test_split
import pandas as pd
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation
from sklearn.preprocessing import OneHotEncoder
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn import datasets
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error


def condition(r):
    if (0 <= r <= 5):
        label = 4
    else:
        label = 7
    return label

In [2]:
df = pd.read_csv("/Users/chandankumar/Documents/Datasets/WineData3a.csv", header=0)
df.head()

fixed  volatile  citric  sugar  chlorides  free  total  density    pH  \
0    7.4      0.70    0.00    1.9      0.076  11.0   34.0   0.9978  3.51   
1    7.8      0.88    0.00    2.6      0.098  25.0   67.0   0.9968  3.20   
2    7.8      0.76    0.04    2.3      0.092  15.0   54.0   0.9970  3.26   
3   11.2      0.28    0.56    1.9      0.075  17.0   60.0   0.9980  3.16   
4    7.4      0.70    0.00    1.9      0.076  11.0   34.0   0.9978  3.51   

   sulphates  alcohol  quality  
0       0.56      9.4        5  
1       0.68      9.8        5  
2       0.65      9.8        5  
3       0.58      9.8        6  
4       0.56      9.4        5

In [3]:
df["quality_class"] = df['quality'].apply(lambda x: condition(x))
df.head()

fixed  volatile  citric  sugar  chlorides  free  total  density    pH  \
0    7.4      0.70    0.00    1.9      0.076  11.0   34.0   0.9978  3.51   
1    7.8      0.88    0.00    2.6      0.098  25.0   67.0   0.9968  3.20   
2    7.8      0.76    0.04    2.3      0.092  15.0   54.0   0.9970  3.26   
3   11.2      0.28    0.56    1.9      0.075  17.0   60.0   0.9980  3.16   
4    7.4      0.70    0.00    1.9      0.076  11.0   34.0   0.9978  3.51   

   sulphates  alcohol  quality  quality_class  
0       0.56      9.4        5              4  
1       0.68      9.8        5              4  
2       0.65      9.8        5              4  
3       0.58      9.8        6              7  
4       0.56      9.4        5              4

In [4]:
X = df[['fixed', 'volatile', 'citric', 'sugar', 'chlorides', 'free', 'total',
       'density', 'pH', 'sulphates', 'alcohol']]
y = df['quality_class']

In [5]:
lst = [0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95]
for ls in lst:
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=(1-ls), random_state=0)
    gbClassifier = GradientBoostingClassifier(random_state=0)
    gbClassifier.fit(X_train, y_train)
    predictions = gbClassifier.predict(X_test)
    score = gbClassifier.score(X_test, y_test)
    # Use score method to get accuracy of model
    print("\n---------------------------------")
    print("Test Size: ", round(1-ls,2))
    print("-----------------------------------")
    print("Accuracy: ", score)
    # print(score)
    cm = metrics.confusion_matrix(y_test, predictions)
    tn, fp, fn, tp = metrics.confusion_matrix(y_test, predictions).ravel()
    print("Confusion Matrix: ")
    print(cm)
    sensitivity_or_recall = tp/(tp+fn)
    specificity = tn/(tn+fp)
    precison = tp/(tp+fp)
    F1Score = (2*tp)/((2*tp)+fp+fn)
    print("Recall: ", sensitivity_or_recall)
    print("Specificity: ", specificity)
    print("Precision: ", precison)
    print("F1 - Score: ", F1Score )
    r2 = r2_score(y_test, predictions)
    print("R Squared: ", r2)
    # print(r2)
    mse = mean_squared_error(y_test, predictions)
    print("Mean Squared Error", np.sqrt(mse))


---------------------------------
Test Size:  0.5
-----------------------------------
Accuracy:  0.75
Confusion Matrix: 
[[262 114]
 [ 86 338]]
Recall:  0.7971698113207547
Specificity:  0.6968085106382979
Precision:  0.7477876106194691
F1 - Score:  0.771689497716895
R Squared:  -0.0036130068245687763
Mean Squared Error 1.5

---------------------------------
Test Size:  0.45
-----------------------------------
Accuracy:  0.75
Confusion Matrix: 
[[239 101]
 [ 79 301]]
Recall:  0.7921052631578948
Specificity:  0.7029411764705882
Precision:  0.7487562189054726
F1 - Score:  0.7698209718670077
R Squared:  -0.003095975232198178
Mean Squared Error 1.5

---------------------------------
Test Size:  0.4
-----------------------------------
Accuracy:  0.7484375
Confusion Matrix: 
[[212  94]
 [ 67 267]]
Recall:  0.7994011976047904
Specificity:  0.6928104575163399
Precision:  0.739612188365651
F1 - Score:  0.7683453237410072
R Squared:  -0.008179718993385654
Mean Squared Error 1.504680198580416

--