## Random Forest classifier

In [1]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import train_test_split
import pandas as pd
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation
from sklearn.preprocessing import OneHotEncoder
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn import datasets
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error


def condition(r):
    if (0 <= r <= 5):
        label = 4
    else:
        label = 7
    return label

In [2]:
df = pd.read_csv("/Users/chandankumar/Documents/Datasets/WineData3a.csv", header=0)
df.head()

fixed  volatile  citric  sugar  chlorides  free  total  density    pH  \
0    7.4      0.70    0.00    1.9      0.076  11.0   34.0   0.9978  3.51   
1    7.8      0.88    0.00    2.6      0.098  25.0   67.0   0.9968  3.20   
2    7.8      0.76    0.04    2.3      0.092  15.0   54.0   0.9970  3.26   
3   11.2      0.28    0.56    1.9      0.075  17.0   60.0   0.9980  3.16   
4    7.4      0.70    0.00    1.9      0.076  11.0   34.0   0.9978  3.51   

   sulphates  alcohol  quality  
0       0.56      9.4        5  
1       0.68      9.8        5  
2       0.65      9.8        5  
3       0.58      9.8        6  
4       0.56      9.4        5

In [3]:
df["quality_class"] = df['quality'].apply(lambda x: condition(x))
df.head()

fixed  volatile  citric  sugar  chlorides  free  total  density    pH  \
0    7.4      0.70    0.00    1.9      0.076  11.0   34.0   0.9978  3.51   
1    7.8      0.88    0.00    2.6      0.098  25.0   67.0   0.9968  3.20   
2    7.8      0.76    0.04    2.3      0.092  15.0   54.0   0.9970  3.26   
3   11.2      0.28    0.56    1.9      0.075  17.0   60.0   0.9980  3.16   
4    7.4      0.70    0.00    1.9      0.076  11.0   34.0   0.9978  3.51   

   sulphates  alcohol  quality  quality_class  
0       0.56      9.4        5              4  
1       0.68      9.8        5              4  
2       0.65      9.8        5              4  
3       0.58      9.8        6              7  
4       0.56      9.4        5              4

In [4]:
# X, y = make_classification(n_samples=1000, n_features=12, n_informative=2, n_redundant=0, random_state=0, shuffle=False)

In [5]:
# y

In [6]:
X = df[['fixed', 'volatile', 'citric', 'sugar', 'chlorides', 'free', 'total',
       'density', 'pH', 'sulphates', 'alcohol']]
y = df['quality_class']

In [7]:
lst = [0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95]
for ls in lst:
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=(1-ls), random_state=0)
    rfClassifier = RandomForestClassifier(max_depth=2, random_state=0)
    rfClassifier.fit(X_train, y_train)
    predictions = rfClassifier.predict(X_test)
    score = rfClassifier.score(X_test, y_test)
    # Use score method to get accuracy of model
    print("\n---------------------------------")
    print("Test Size: ", round(1-ls,2))
    print("-----------------------------------")
    print("Accuracy: ", score)
    # print(score)
    cm = metrics.confusion_matrix(y_test, predictions)
    tn, fp, fn, tp = metrics.confusion_matrix(y_test, predictions).ravel()
#     print("TN: ", tn)
#     print("FP: ", fp)
#     print("FN: ", fn)
#     print("TP: ", tp)
    print("Confusion Matrix: ")
    print(cm)
    sensitivity_or_recall = tp/(tp+fn)
    specificity = tn/(tn+fp)
    precison = tp/(tp+fp)
    F1Score = (2*tp)/((2*tp)+fp+fn)
    print("Recall: ", sensitivity_or_recall)
    print("Specificity: ", specificity)
    print("Precision: ", precison)
    print("F1 - Score: ", F1Score )
    r2 = r2_score(y_test, predictions)
    print("R Squared: ", r2)
    # print(r2)
    mse = mean_squared_error(y_test, predictions)
    print("Root Mean Squared Error", np.sqrt(mse))


---------------------------------
Test Size:  0.5
-----------------------------------
Accuracy:  0.69875
Confusion Matrix: 
[[217 159]
 [ 82 342]]
Recall:  0.8066037735849056
Specificity:  0.5771276595744681
Precision:  0.6826347305389222
F1 - Score:  0.7394594594594595
R Squared:  -0.2093536732236052
Root Mean Squared Error 1.6465873800075113

---------------------------------
Test Size:  0.45
-----------------------------------
Accuracy:  0.7013888888888888
Confusion Matrix: 
[[197 143]
 [ 72 308]]
Recall:  0.8105263157894737
Specificity:  0.5794117647058824
Precision:  0.6829268292682927
F1 - Score:  0.7412755716004813
R Squared:  -0.19814241486068118
Root Mean Squared Error 1.6393596310755

---------------------------------
Test Size:  0.4
-----------------------------------
Accuracy:  0.721875
Confusion Matrix: 
[[186 120]
 [ 58 276]]
Recall:  0.8263473053892215
Specificity:  0.6078431372549019
Precision:  0.696969696969697
F1 - Score:  0.7561643835616438
R Squared:  -0.114633478

/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The de

In [8]:
lst = [0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95]
for ls in lst:
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=(1-ls), random_state=0)
    rfClassifier = RandomForestClassifier(max_depth=2, random_state=0)
    rfClassifier.fit(X_train, y_train)
    predictions = rfClassifier.predict(X_test)
    score = rfClassifier.score(X_test, y_test)
    # Use score method to get accuracy of model
    print("\n---------------------------------")
    print("Test Size: ", round(1-ls,2))
    print("-----------------------------------")
    print("Accuracy: ", score)
    # print(score)
    cm = metrics.confusion_matrix(y_test, predictions)
    tn, fp, fn, tp = metrics.confusion_matrix(y_test, predictions).ravel()
    print("TN: ", tn)
    print("FP: ", fp)
    print("FN: ", fn)
    print("TP: ", tp)
    print("Confusion Matrix: ")
    print(cm)
    sensitivity_or_recall = tp/(tp+fn)
    specificity = tn/(tn+fp)
    precison = tp/(tp+fp)
    F1Score = (2*tp)/((2*tp)+fp+fn)
    print("Recall: ", sensitivity_or_recall)
    print("Specificity: ", specificity)
    print("Precision: ", precison)
    print("F1 - Score: ", F1Score )
    r2 = r2_score(y_test, predictions)
    print("R Squared: ", r2)
    # print(r2)
    mse = mean_squared_error(y_test, predictions)
    print("Root Mean Squared Error", np.sqrt(mse))

/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The de


---------------------------------
Test Size:  0.5
-----------------------------------
Accuracy:  0.69875
TN:  217
FP:  159
FN:  82
TP:  342
Confusion Matrix: 
[[217 159]
 [ 82 342]]
Recall:  0.8066037735849056
Specificity:  0.5771276595744681
Precision:  0.6826347305389222
F1 - Score:  0.7394594594594595
R Squared:  -0.2093536732236052
Root Mean Squared Error 1.6465873800075113

---------------------------------
Test Size:  0.45
-----------------------------------
Accuracy:  0.7013888888888888
TN:  197
FP:  143
FN:  72
TP:  308
Confusion Matrix: 
[[197 143]
 [ 72 308]]
Recall:  0.8105263157894737
Specificity:  0.5794117647058824
Precision:  0.6829268292682927
F1 - Score:  0.7412755716004813
R Squared:  -0.19814241486068118
Root Mean Squared Error 1.6393596310755

---------------------------------
Test Size:  0.4
-----------------------------------
Accuracy:  0.721875
TN:  186
FP:  120
FN:  58
TP:  276
Confusion Matrix: 
[[186 120]
 [ 58 276]]
Recall:  0.8263473053892215
Specificity:  