In [1]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.model_selection import train_test_split # Import train_test_split function
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation
from sklearn.preprocessing import OneHotEncoder
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn import datasets
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

def condition(r):
    if (0 <= r <= 5):
        label = 4
    else:
        label = 7
    return label



In [2]:
df = pd.read_csv("/Users/chandankumar/Documents/Datasets/WineData3a.csv", header=0)
df.head()

fixed  volatile  citric  sugar  chlorides  free  total  density    pH  \
0    7.4      0.70    0.00    1.9      0.076  11.0   34.0   0.9978  3.51   
1    7.8      0.88    0.00    2.6      0.098  25.0   67.0   0.9968  3.20   
2    7.8      0.76    0.04    2.3      0.092  15.0   54.0   0.9970  3.26   
3   11.2      0.28    0.56    1.9      0.075  17.0   60.0   0.9980  3.16   
4    7.4      0.70    0.00    1.9      0.076  11.0   34.0   0.9978  3.51   

   sulphates  alcohol  quality  
0       0.56      9.4        5  
1       0.68      9.8        5  
2       0.65      9.8        5  
3       0.58      9.8        6  
4       0.56      9.4        5

In [3]:
df["quality_class"] = df['quality'].apply(lambda x: condition(x))
df.head()

fixed  volatile  citric  sugar  chlorides  free  total  density    pH  \
0    7.4      0.70    0.00    1.9      0.076  11.0   34.0   0.9978  3.51   
1    7.8      0.88    0.00    2.6      0.098  25.0   67.0   0.9968  3.20   
2    7.8      0.76    0.04    2.3      0.092  15.0   54.0   0.9970  3.26   
3   11.2      0.28    0.56    1.9      0.075  17.0   60.0   0.9980  3.16   
4    7.4      0.70    0.00    1.9      0.076  11.0   34.0   0.9978  3.51   

   sulphates  alcohol  quality  quality_class  
0       0.56      9.4        5              4  
1       0.68      9.8        5              4  
2       0.65      9.8        5              4  
3       0.58      9.8        6              7  
4       0.56      9.4        5              4

In [4]:
X = df[['fixed', 'volatile', 'citric', 'sugar', 'chlorides', 'free', 'total',
       'density', 'pH', 'sulphates', 'alcohol']]
y = df['quality_class']

In [5]:
lst = [0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95]
for ls in lst:
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=(1-ls), random_state=0)
    dtClassifier = DecisionTreeClassifier()
    dtClassifier.fit(X_train, y_train)
    predictions = dtClassifier.predict(X_test)
    score = dtClassifier.score(X_test, y_test)
    # Use score method to get accuracy of model
    print("\n---------------------------------")
    print("Test Size: ", round(1-ls,2))
    print("-----------------------------------")
    print("Accuracy: ", score)
    # print(score)
    cm = metrics.confusion_matrix(y_test, predictions)
    tn, fp, fn, tp = metrics.confusion_matrix(y_test, predictions).ravel()
    print("Confusion Matrix: ")
    print(cm)
    sensitivity_or_recall = tp/(tp+fn)
    specificity = tn/(tn+fp)
    precison = tp/(tp+fp)
    F1Score = (2*tp)/((2*tp)+fp+fn)
    print("Recall: ", sensitivity_or_recall)
    print("Specificity: ", specificity)
    print("Precision: ", precison)
    print("F1 - Score: ", F1Score )
    r2 = r2_score(y_test, predictions)
    print("R Squared: ", r2)
    # print(r2)
    mse = mean_squared_error(y_test, predictions)
    print("Root Mean Squared Error", np.sqrt(mse))


---------------------------------
Test Size:  0.5
-----------------------------------
Accuracy:  0.7125
Confusion Matrix: 
[[254 122]
 [108 316]]
Recall:  0.7452830188679245
Specificity:  0.675531914893617
Precision:  0.7214611872146118
F1 - Score:  0.7331786542923434
R Squared:  -0.15415495784825395
Root Mean Squared Error 1.6085707942145413

---------------------------------
Test Size:  0.45
-----------------------------------
Accuracy:  0.7347222222222223
Confusion Matrix: 
[[233 107]
 [ 84 296]]
Recall:  0.7789473684210526
Specificity:  0.6852941176470588
Precision:  0.7344913151364765
F1 - Score:  0.756066411238825
R Squared:  -0.06439628482972126
Root Mean Squared Error 1.5451537140362444

---------------------------------
Test Size:  0.4
-----------------------------------
Accuracy:  0.696875
Confusion Matrix: 
[[200 106]
 [ 88 246]]
Recall:  0.7365269461077845
Specificity:  0.6535947712418301
Precision:  0.6988636363636364
F1 - Score:  0.717201166180758
R Squared:  -0.21482525