## Logistic Regression Classifier

In [8]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn import datasets
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

def condition(r):
    if (0 <= r <= 5):
        label = 4
    else:
        label = 7
    return label



# def condition(r):
#     if (0 <= r <= 5):
#         label = "averge"
#     else:
#         label = "better"
#     return label


# def transData(data):
#     return data.rdd.map(lambda r: [Vectors.dense(r[:-1]), r[-1]]).toDF(['features', 'label'])

# df_C["quality_class"] = df_C['quality'].apply(lambda x: condition(x))


In [9]:
df = pd.read_csv("/Users/chandankumar/Documents/Datasets/WineData3a.csv", header=0)
df.head()

fixed  volatile  citric  sugar  chlorides  free  total  density    pH  \
0    7.4      0.70    0.00    1.9      0.076  11.0   34.0   0.9978  3.51   
1    7.8      0.88    0.00    2.6      0.098  25.0   67.0   0.9968  3.20   
2    7.8      0.76    0.04    2.3      0.092  15.0   54.0   0.9970  3.26   
3   11.2      0.28    0.56    1.9      0.075  17.0   60.0   0.9980  3.16   
4    7.4      0.70    0.00    1.9      0.076  11.0   34.0   0.9978  3.51   

   sulphates  alcohol  quality  
0       0.56      9.4        5  
1       0.68      9.8        5  
2       0.65      9.8        5  
3       0.58      9.8        6  
4       0.56      9.4        5

In [10]:
df.quality.unique()

array([5, 6, 7, 4, 8, 3])

In [11]:
df["quality_class"] = df['quality'].apply(lambda x: condition(x))
df.head()

fixed  volatile  citric  sugar  chlorides  free  total  density    pH  \
0    7.4      0.70    0.00    1.9      0.076  11.0   34.0   0.9978  3.51   
1    7.8      0.88    0.00    2.6      0.098  25.0   67.0   0.9968  3.20   
2    7.8      0.76    0.04    2.3      0.092  15.0   54.0   0.9970  3.26   
3   11.2      0.28    0.56    1.9      0.075  17.0   60.0   0.9980  3.16   
4    7.4      0.70    0.00    1.9      0.076  11.0   34.0   0.9978  3.51   

   sulphates  alcohol  quality  quality_class  
0       0.56      9.4        5              4  
1       0.68      9.8        5              4  
2       0.65      9.8        5              4  
3       0.58      9.8        6              7  
4       0.56      9.4        5              4

In [12]:
X = df[['fixed', 'volatile', 'citric', 'sugar', 'chlorides', 'free', 'total',
       'density', 'pH', 'sulphates', 'alcohol']]
y = df['quality_class']

In [13]:
lst = [0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95]
for ls in lst:
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=(1-ls), random_state=0)
    logisticRegr = LogisticRegression()
    logisticRegr.fit(X_train, y_train)
    predictions = logisticRegr.predict(X_test)
    score = logisticRegr.score(X_test, y_test)
    # Use score method to get accuracy of model
    print("\n---------------------------------")
    print("Test Size: ", round(1-ls,2))
    print("-----------------------------------")
    print("Accuracy: ", score)
    # print(score)
    cm = metrics.confusion_matrix(y_test, predictions)
    tn, fp, fn, tp = metrics.confusion_matrix(y_test, predictions).ravel()
    print("Confusion Matrix: ")
    print(cm)
    sensitivity_or_recall = tp/(tp+fn)
    specificity = tn/(tn+fp)
    precison = tp/(tp+fp)
    F1Score = (2*tp)/((2*tp)+fp+fn)
    print("Recall: ", sensitivity_or_recall)
    print("Specificity: ", specificity)
    print("Precision: ", precison)
    print("F1 - Score: ", F1Score )
    r2 = r2_score(y_test, predictions)
    print("R Squared: ", r2)
    # print(r2)
    mse = mean_squared_error(y_test, predictions)
    print("Root Mean Squared Error", np.sqrt(mse))


---------------------------------
Test Size:  0.5
-----------------------------------
Accuracy:  0.72875
Confusion Matrix: 
[[256 120]
 [ 97 327]]
Recall:  0.7712264150943396
Specificity:  0.6808510638297872
Precision:  0.7315436241610739
F1 - Score:  0.7508610792192881
R Squared:  -0.08892011240465703
Root Mean Squared Error 1.5624499991999745

---------------------------------
Test Size:  0.45
-----------------------------------
Accuracy:  0.7361111111111112
Confusion Matrix: 
[[231 109]
 [ 81 299]]
Recall:  0.7868421052631579
Specificity:  0.6794117647058824
Precision:  0.7328431372549019
F1 - Score:  0.7588832487309645
R Squared:  -0.05882352941176472
Root Mean Squared Error 1.541103500742244

---------------------------------
Test Size:  0.4
-----------------------------------
Accuracy:  0.7375
Confusion Matrix: 
[[205 101]
 [ 67 267]]
Recall:  0.7994011976047904
Specificity:  0.6699346405228758
Precision:  0.7255434782608695
F1 - Score:  0.7606837606837606
R Squared:  -0.0520136

/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  Futur