In [1]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import metrics
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

In [2]:
df = pd.read_csv("/Users/chandankumar/Documents/Datasets/WineData3a.csv", header=0)
df.head()

fixed  volatile  citric  sugar  chlorides  free  total  density    pH  \
0    7.4      0.70    0.00    1.9      0.076  11.0   34.0   0.9978  3.51   
1    7.8      0.88    0.00    2.6      0.098  25.0   67.0   0.9968  3.20   
2    7.8      0.76    0.04    2.3      0.092  15.0   54.0   0.9970  3.26   
3   11.2      0.28    0.56    1.9      0.075  17.0   60.0   0.9980  3.16   
4    7.4      0.70    0.00    1.9      0.076  11.0   34.0   0.9978  3.51   

   sulphates  alcohol  quality  
0       0.56      9.4        5  
1       0.68      9.8        5  
2       0.65      9.8        5  
3       0.58      9.8        6  
4       0.56      9.4        5

In [3]:
df.columns

Index(['fixed', 'volatile', 'citric', 'sugar', 'chlorides', 'free', 'total',
       'density', 'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [4]:
X = df[['fixed', 'volatile', 'citric', 'sugar', 'chlorides', 'free', 'total',
       'density', 'pH', 'sulphates', 'alcohol']]
y = df['quality']

In [8]:
y.value_counts()

5    681
6    638
7    199
4     53
8     18
3     10
Name: quality, dtype: int64

In [24]:
lst = [0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95]
for ls in lst:
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=(1-ls), random_state=0)
    logisticRegr = LogisticRegression()
    logisticRegr.fit(X_train, y_train)
    predictions = logisticRegr.predict(X_test)
    score = logisticRegr.score(X_test, y_test)
    # Use score method to get accuracy of model
    print("Accuracy")
    print(score)
    cm = metrics.confusion_matrix(y_test, predictions)
    print("Confusion Matrix")
    print(cm)
    print("R Squared")
    r2 = r2_score(y_test, predictions)
    print(r2)
    print("Mean Squared Error")
    mse = mean_squared_error(y_test, predictions)
    print(mse)

/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed

Accuracy
0.60125
Confusion Matrix
[[  0   0   5   0   0   0]
 [  0   0  17   7   2   0]
 [  0   0 258  86   1   0]
 [  0   0 114 205  14   0]
 [  0   0   7  57  18   0]
 [  0   0   0   5   4   0]]
R Squared
0.16381138848099186
Mean Squared Error
0.5125
Accuracy
0.6013888888888889
Confusion Matrix
[[  0   0   4   0   0   0]
 [  0   0  15   9   2   0]
 [  0   0 232  77   1   0]
 [  0   0 102 182  17   0]
 [  0   0   6  45  19   0]
 [  0   0   0   5   4   0]]
R Squared
0.1455588903818864
Mean Squared Error
0.525
Accuracy
0.6171875
Confusion Matrix
[[  0   0   4   0   0   0]
 [  0   0  12   9   2   0]
 [  0   0 210  68   1   0]
 [  0   0  81 171  16   0]
 [  0   0   4  42  14   0]
 [  0   0   0   3   3   0]]
R Squared
0.15021617523512898
Mean Squared Error
0.50625
Accuracy
0.6196428571428572
Confusion Matrix
[[  0   0   4   0   0   0]
 [  0   0  13   4   0   0]
 [  0   0 186  58   1   0]
 [  0   0  73 149  16   0]
 [  0   0   4  35  12   0]
 [  0   0   0   3   2   0]]
R Squared
0.198244651

/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
logisticRegr = LogisticRegression()
logisticRegr.fit(X_train, y_train)

/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [15]:
predictions = logisticRegr.predict(X_test)

In [17]:
predictions

array([6, 5, 6, 5, 6, 5, 5, 6, 5, 5, 5, 5, 6, 5, 6, 6, 7, 6, 6, 5, 6, 5,
       6, 5, 5, 5, 5, 6, 5, 6, 6, 6, 6, 5, 6, 6, 5, 5, 6, 6, 5, 6, 7, 6,
       6, 5, 6, 6, 5, 6, 5, 5, 6, 6, 5, 5, 5, 5, 6, 5, 5, 6, 6, 6, 5, 6,
       5, 6, 6, 6, 5, 5, 5, 5, 5, 6, 5, 5, 5, 6, 5, 5, 6, 6, 6, 5, 6, 5,
       5, 5, 5, 5, 6, 5, 6, 5, 6, 5, 5, 6, 7, 6, 6, 6, 5, 5, 5, 5, 6, 5,
       6, 5, 6, 5, 6, 6, 6, 7, 6, 6, 5, 6, 6, 5, 6, 6, 5, 5, 6, 6, 5, 5,
       6, 6, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 6, 6, 6, 6, 5, 6, 6, 5, 6,
       6, 6, 5, 5, 6, 6, 6, 6, 6, 5, 6, 5, 6, 6, 5, 6, 6, 5, 5, 7, 6, 6,
       7, 7, 6, 5, 5, 7, 5, 6, 7, 5, 6, 6, 5, 6, 6, 6, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 6, 5, 5, 5, 5, 5, 6, 6, 5, 6, 5, 6, 7, 5, 5, 6, 6, 6, 5,
       5, 6, 6, 6, 5, 6, 6, 6, 5, 5, 5, 6, 5, 6, 6, 6, 6, 6, 7, 6, 5, 5,
       5, 5, 6, 5, 5, 5, 5, 6, 5, 5, 5, 5, 6, 5, 5, 5, 5, 5, 5, 7, 5, 6,
       5, 5, 5, 5, 6, 6, 5, 6, 6, 6, 6, 6, 6, 5, 7, 6, 5, 7, 6, 6, 6, 5,
       5, 5, 6, 6, 6, 6, 6, 5, 5, 6, 5, 5, 5, 5, 6,

In [18]:
score = logisticRegr.score(X_test, y_test)
print(score)

0.6291666666666667


## Decision Tree Regression

In [105]:
from sklearn.tree import DecisionTreeRegressor
import matplotlib.pyplot as plt
from sklearn.metrics import r2_score,mean_squared_error
import numpy as np
from sklearn import metrics

df = pd.read_csv("/Users/chandankumar/Documents/Datasets/WineData3a.csv", header=0)
df.head()

fixed  volatile  citric  sugar  chlorides  free  total  density    pH  \
0    7.4      0.70    0.00    1.9      0.076  11.0   34.0   0.9978  3.51   
1    7.8      0.88    0.00    2.6      0.098  25.0   67.0   0.9968  3.20   
2    7.8      0.76    0.04    2.3      0.092  15.0   54.0   0.9970  3.26   
3   11.2      0.28    0.56    1.9      0.075  17.0   60.0   0.9980  3.16   
4    7.4      0.70    0.00    1.9      0.076  11.0   34.0   0.9978  3.51   

   sulphates  alcohol  quality  
0       0.56      9.4        5  
1       0.68      9.8        5  
2       0.65      9.8        5  
3       0.58      9.8        6  
4       0.56      9.4        5

In [106]:
X = df[['fixed', 'volatile', 'citric', 'sugar', 'chlorides', 'free', 'total',
       'density', 'pH', 'sulphates', 'alcohol']]
y = df['quality']

In [111]:
lst = [0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95]
for ls in lst:
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=(1-ls), random_state=0)
    regr_1 = DecisionTreeRegressor(max_depth=10)
    regr_1.fit(X_train, y_train)
    y_predict = regr_1.predict(X_test)
    mse = mean_squared_error(y_test, y_predict)
    rmse = np.sqrt(mse)
    print("\n---------------------------------")
    print("Test Size: ", (1-ls))
    print("-----------------------------------")
    print("Root Mean Square Error: ", rmse)
    df2 =pd.DataFrame({'Actual':y_test, 'Predicted':y_predict})
    df2['diff'] = np.abs(pd.eval('(y_test-y_predict)/y_test'))
    df2['acc'] = 1 - df2['diff']
    accuracy = df2['acc'].mean()
    print("Accuracy is: ", accuracy)
    print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_predict))
    print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_predict))
    print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_predict)))
    print("Variance :", np.var(pd.eval('y_test-y_predict')))
    print("R Squred :", r2_score(y_test,y_predict))


---------------------------------
Test Size:  0.5
-----------------------------------
Root Mean Square Error:  0.7942285936844211
Accuracy is:  0.90380542245294
Mean Absolute Error: 0.513879770512279
Mean Squared Error: 0.6307990590259334
Root Mean Squared Error: 0.7942285936844211
Variance : 0.6259986334046055
R Squred : -0.029203881589057623

---------------------------------
Test Size:  0.44999999999999996
-----------------------------------
Root Mean Square Error:  0.8257785895857661
Accuracy is:  0.8992452554319451
Mean Absolute Error: 0.5480512453414252
Mean Squared Error: 0.6819102790182572
Root Mean Squared Error: 0.8257785895857661
Variance : 0.6810552383391277
R Squred : -0.10981366755115651

---------------------------------
Test Size:  0.4
-----------------------------------
Root Mean Square Error:  0.7868163758195363
Accuracy is:  0.9056436953627527
Mean Absolute Error: 0.504104570357365
Mean Squared Error: 0.6190800092577898
Root Mean Squared Error: 0.7868163758195363
Va

## Gradient Boosted Decision Tree Regressor

In [159]:
from sklearn.datasets import make_regression
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import train_test_split


import numpy as np
import pandas as pd
%matplotlib inline
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn.metrics import mean_squared_error

from sklearn import ensemble
from sklearn.metrics import mean_squared_error, r2_score


df = pd.read_csv("/Users/chandankumar/Documents/Datasets/WineData3a.csv", header=0)
df.head()

fixed  volatile  citric  sugar  chlorides  free  total  density    pH  \
0    7.4      0.70    0.00    1.9      0.076  11.0   34.0   0.9978  3.51   
1    7.8      0.88    0.00    2.6      0.098  25.0   67.0   0.9968  3.20   
2    7.8      0.76    0.04    2.3      0.092  15.0   54.0   0.9970  3.26   
3   11.2      0.28    0.56    1.9      0.075  17.0   60.0   0.9980  3.16   
4    7.4      0.70    0.00    1.9      0.076  11.0   34.0   0.9978  3.51   

   sulphates  alcohol  quality  
0       0.56      9.4        5  
1       0.68      9.8        5  
2       0.65      9.8        5  
3       0.58      9.8        6  
4       0.56      9.4        5

In [160]:
X = df[['fixed', 'volatile', 'citric', 'sugar', 'chlorides', 'free', 'total',
       'density', 'pH', 'sulphates', 'alcohol']]
y = df['quality']

In [172]:
lst = [0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95]
for ls in lst:
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=(1-ls), random_state=234, shuffle=True)
    params = {'n_estimators': 500, 'max_depth': 4, 'min_samples_split': 2, 'learning_rate': 0.01, 'loss': 'ls'}
    model = ensemble.GradientBoostingRegressor(**params)
    model.fit(X_train, y_train)
    model_score = model.score(X_train,y_train)
    print("\n---------------------------------")
    print("Test Size: ", (1-ls))
    print("-----------------------------------")
    print('R Squared : ', model_score)
    y_predicted = model.predict(X_test)
    # The mean squared error
    print("Mean squared error: %.2f"% mean_squared_error(y_test, y_predicted))
    print("Root Mean squared error: ", np.sqrt(mean_squared_error(y_test, y_predicted)))
    # Explained variance score: 1 is perfect prediction
    print('Test Variance score: %.2f' % r2_score(y_test, y_predicted))
    df3 =pd.DataFrame({'Actual_1':y_test, 'Predicted_1':y_predicted})
    df3['diff_1'] = np.abs(pd.eval('(y_test-y_predicted)/y_test'))
    df3['acc_1'] = 1 - df3['diff_1']
    accuracy_1 = df3['acc_1'].mean()
    print("Accuracy is: ", accuracy_1)
    


---------------------------------
Test Size:  0.5
-----------------------------------
R Squared :  0.7151516008761971
Mean squared error: 0.38
Root Mean squared error:  0.618929327437662
Test Variance score: 0.42
Accuracy is:  0.9130375111907886

---------------------------------
Test Size:  0.44999999999999996
-----------------------------------
R Squared :  0.6989066555342502
Mean squared error: 0.39
Root Mean squared error:  0.6227568088826404
Test Variance score: 0.41
Accuracy is:  0.9110535454827628

---------------------------------
Test Size:  0.4
-----------------------------------
R Squared :  0.6895501763222235
Mean squared error: 0.36
Root Mean squared error:  0.5986888962217952
Test Variance score: 0.45
Accuracy is:  0.9134060424698985

---------------------------------
Test Size:  0.35
-----------------------------------
R Squared :  0.686073009743898
Mean squared error: 0.37
Root Mean squared error:  0.6082141097657343
Test Variance score: 0.44
Accuracy is:  0.9126408817

## Random Forest Regressor

In [174]:
import numpy as np
import pandas as pd
%matplotlib inline
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn.metrics import mean_squared_error

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

df = pd.read_csv("/Users/chandankumar/Documents/Datasets/WineData3a.csv", header=0)
df.head()

fixed  volatile  citric  sugar  chlorides  free  total  density    pH  \
0    7.4      0.70    0.00    1.9      0.076  11.0   34.0   0.9978  3.51   
1    7.8      0.88    0.00    2.6      0.098  25.0   67.0   0.9968  3.20   
2    7.8      0.76    0.04    2.3      0.092  15.0   54.0   0.9970  3.26   
3   11.2      0.28    0.56    1.9      0.075  17.0   60.0   0.9980  3.16   
4    7.4      0.70    0.00    1.9      0.076  11.0   34.0   0.9978  3.51   

   sulphates  alcohol  quality  
0       0.56      9.4        5  
1       0.68      9.8        5  
2       0.65      9.8        5  
3       0.58      9.8        6  
4       0.56      9.4        5

In [175]:
X = df[['fixed', 'volatile', 'citric', 'sugar', 'chlorides', 'free', 'total',
       'density', 'pH', 'sulphates', 'alcohol']]
y = df['quality']

In [176]:
lst = [0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95]
for ls in lst:
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=(1-ls), random_state=234, shuffle=True)
    # params = {'n_estimators': 500, 'max_depth': 4, 'min_samples_split': 2, 'learning_rate': 0.01, 'loss': 'ls'}
    n_estimators=100
    model = RandomForestRegressor(random_state=0, n_estimators=n_estimators)
    model.fit(X_train, y_train)
    model_score = model.score(X_train,y_train)
    print("\n---------------------------------")
    print("Test Size: ", (1-ls))
    print("-----------------------------------")
    # print('coefficient of determination R^2 of the prediction.: ',model_score)
    print('R Squared : ', model_score)
    y_predicted = model.predict(X_test)
    # The mean squared error
    print("Mean squared error: %.2f"% mean_squared_error(y_test, y_predicted))
    print("Root Mean squared error: ", np.sqrt(mean_squared_error(y_test, y_predicted)))
    # Explained variance score: 1 is perfect prediction
    print('Test Variance score: %.2f' % r2_score(y_test, y_predicted))
    df4 =pd.DataFrame({'Actual_2':y_test, 'Predicted_2':y_predicted})
    df4['diff_2'] = np.abs(pd.eval('(y_test-y_predicted)/y_test'))
    df4['acc_2'] = 1 - df4['diff_2']
    accuracy_2 = df4['acc_2'].mean()
    print("Accuracy is: ", accuracy_2)
    


---------------------------------
Test Size:  0.5
-----------------------------------
R Squared :  0.9165195634458958
Mean squared error: 0.37
Root Mean squared error:  0.6075785957388559
Test Variance score: 0.45
Accuracy is:  0.9166309226190489

---------------------------------
Test Size:  0.44999999999999996
-----------------------------------
R Squared :  0.9151676019228991
Mean squared error: 0.35
Root Mean squared error:  0.5935051249427703
Test Variance score: 0.47
Accuracy is:  0.9180180886243401

---------------------------------
Test Size:  0.4
-----------------------------------
R Squared :  0.9153070998511478
Mean squared error: 0.33
Root Mean squared error:  0.574917113591168
Test Variance score: 0.49
Accuracy is:  0.9212715029761913

---------------------------------
Test Size:  0.35
-----------------------------------
R Squared :  0.9212470888424628
Mean squared error: 0.34
Root Mean squared error:  0.58288062365168
Test Variance score: 0.48
Accuracy is:  0.92040355017